### ISSUE TITLE
after upgrading to last nunit 3 rc, adpater no longer can debug failed tests

### ISSUE THREAD

**Issue by jmecosta** [nunit/nunit-vs-adapter#86]
Hi,

Seems tests that pass i am able to debug, tests that fail i cannot and i get this exception:

Exception thrown executing tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\AssemblyPatcherTask.Test.dll
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Invalid filter element: tests
Parameter name: xmlNode
   at NUnit.Framework.Internal.TestFilter.FromXml(TNode node)
   at NUnit.Framework.Internal.TestFilter.FromXml(String xmlText)
   at NUnit.Framework.Api.FrameworkController.CountTests(ICallbackEventHandler handler, String filter)
   at NUnit.Framework.Api.FrameworkController.CountTestsAction..ctor(FrameworkController controller, String filter, Object handler)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(String typeName, Object[] args)
   at NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.DirectTestRunner.CountTests(TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.CountTests(TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.CountTestCases(TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.RunTests(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.AbstractTestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.Engine.Runners.MasterTestRunner.NUnit.Engine.ITestRunner.Run(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.RunnerWrapper.RunInternal(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.RunnerWrapper.RunInternal(ITestEventListener listener, TestFilter filter)
   at NUnit.VisualStudio.TestAdapter.NUnit3TestExecutor.RunAssembly(String assemblyName, IFrameworkHandle frameworkHandle)
NUnit Adapter 3.0.2.0 executing tests is finished
========== Run test finished: 0 run (0:00:05,5349757) ==========

Is there already some new version of the adpater that i am not aware?

thanks and regards

jorge costa

**Comment by jmecosta** [comment]
and i get loads of duplicate tests provided by the explorer. i am using vs 2013 and i dont have nunit 2 adpater installed

**Comment by jmecosta** [comment]
![image](https://cloud.githubusercontent.com/assets/1041352/10903510/223e16b2-8213-11e5-9a70-ffa1103c155c.png)

if trying to debug the blue tests i get the exception above, the green ones work fine.

ive check all my extensions and i dont have any extension that could provide a those duplicate entries.

this is the log during discovery:

------ Run test started ------
NUnit Adapter 3.0.2.0 executing tests is started
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\AssemblyPatcherTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\AssemblyPatcherTask.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppCheckTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppCheckTask.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppLintTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppLintTask.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\MsbuildTaskUtils.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\MsbuildTaskUtils.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\NunitRunnerTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\NunitRunnerTask.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\RatsTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\RatsTask.Test.dll
SetUp failed for test fixture RatsTask.Test.RatsTest
System.IO.FileNotFoundException : Could not find file 'C:\WINDOWS\system32\rats-report.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at RatsTask.Test.RatsTest..ctor() in D:\prod\tools\MSBuild-SonarQube-CXX\CppTasks\RatsTask.Test\RatsTaskTest.fs:line 15
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\VeraTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\VeraTask.Test.dll
Running all tests in D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\WindowsApiInteropService.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\WindowsApiInteropService.Test.dll
NUnit Adapter 3.0.2.0 executing tests is finished
NUnit 1.2.0.0 executing tests is started
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\AssemblyPatcherTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\AssemblyPatcherTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppCheckTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppCheckTask.Test.dll
Exception! 
Root element is missing.
Exception! 
Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 10.
Exception! 
Unexpected end tag. Line 1, position 3.
Exception! 
Root element is missing.
Exception! 
Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 10.
<error file="sdsd" line="4" id="missingInclude" severity="style" msg="Include file: &quot;cancel_proto.h&quot; not found."/>
Exception! 
Unexpected end tag. Line 1, position 3.
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppLintTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\CppLintTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\MsbuildTaskUtils.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\MsbuildTaskUtils.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\NunitRunnerTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\NunitRunnerTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\RatsTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\RatsTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\VeraTask.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\Test\VeraTask.Test.dll
Loading tests from D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\WindowsApiInteropService.Test.dll
Run started: D:\prod\tools\MSBuild-SonarQube-CXX\BuildDrop\WindowsApiInteropService.Test.dll
NUnit 1.2.0.0 executing tests is finished
========== Run test finished: 72 run (0:00:03,2559683) ==========

**Comment by CharliePoole** [comment]
The last release of the NUnit 3 adapter (CTP-4) works with NUnit beta 4. We
have not yet put out a new release.

**Comment by jmecosta** [comment]
it does work, however seems to have a weird behaviour showing duplicate tests. not sure if you can confirm this. i see this in this repo: https://github.com/SonarOpenCommunity/sonar-cxx-msbuild-tasks

**Comment by CharliePoole** [comment]
Unfortunately, it merely appears to work, at least as I would define
"working" :-)

From beta 5, there are changes to the API that require corresponding
changes to the adapter. Because we are in beta, we have made no attempt to
maintain backward compatibility, which would be extremely difficult anyway.

So the beta 4 core engine, which is embedded in the adapter, is able to see
that the test uses NUnit 3 and **imagines** it knows how to discover and
run the tests correctly. However, it really doesn't.

The next release of  the adapter will be for whatever is current for NUnit
at the time. Unfortunately, at any given moment, I can only be working on
one of the two projects and NUnit itself is taking a lot of time right now.
:-)

**Comment by CharliePoole** [comment]
To clarify, since I would not expect it to work at all, I don't want to
spend time figuring out why you see duplicates using this old version.
Better to spend the time in creating the next version.

**Comment by jmecosta** [comment]
ok, go it. i had the impression you said its supported :) i will wait the the rc thanks
